### PR TITLE
Be more distribution version independent

### PR DESCRIPTION
**Pull request by noonedeadpunk**
This pull request aims to extend list of supported OS versions by using version test. As a result roles can be used with Ubuntu Bionic, Debian Buster (10), etc.
It also drops unnecessary code duplication inside roles

### CODE REVIEW

**Comment by luclis** [comment]
@noonedeadpunk Since I haven't any answer from @tjtoml, J've make my own fork and I'll rework it. 
If you want to (re-)make your PR, you're welcome.

**Comment by noonedeadpunk** [comment]
I've already maintaining my fork, so... Just need to push latest changes Icve made for flawless mattermost upgrade

**Comment by luclis** [comment]
I haven't notice, I'll check your and make PR/my own if it's still needed. 
Thanks for your work, both of you.

**Comment by luclis** [comment]
Thanks you again @noonedeadpunkm I can now merge your PR :)
If you want to make any other, I'll be grateful for you help !

**Pull request merged**
